- hosts: all
  gather_facts: no
  connection: local
  max_fail_percentage: 0

  tasks:

    - name: Create a new instance and attaches to a network and passes metadata to the instance
      os_server:
        state: present
        name: "{{ item }}"
        image: CentOS-7-x86_64-GenericCloud-1708
        key_name: ansible-tower-key
        wait: yes
        timeout: 180
        flavor: m1.small
        nics:
          - net-name: shared-net
        auto_ip: no
        security_groups: open-all
        meta:
          hostname: "{{ item }}"
          group: test_group1
      with_items:
        - vm1-from-tower
        - vm2-from-tower
