- hosts: all
  gather_facts: no
  connection: local
  max_fail_percentage: 0

  tasks:

    - name: Create a new instance and attaches to a network and passes metadata to the instance
      os_server:
        state: present
        name: vm1-from-tower
        image: 9ee1adce-9c17-41d3-8dad-d2222a282dc3
        key_name: ansible-tower-key
        timeout: 200
        flavor: 100
        nics:
          - net-name: shared-net
        meta:
          hostname: test1
          group: test_group1
