- hosts: all
  connection: local
  tasks:
    - ec2_instance_info:
        region: ap-northeast-1
      register: ret

    - debug:
        var: ret

    - ec2:
        key_name: mykey
        instance_type: t2.micro
        image: aw0evgkw8e5c1q413zgy5pjce
        wait: yes
        group: aitac-automation-key
        count: 1
        vpc_subnet_id: subnet-41ab9008
        assign_public_ip: yes
        region: ap-northeast-1
