- hosts: all
  connection: local
  tasks:
    - name: Collect instance info
      ec2_instance_info:
        region: ap-northeast-1
        filters:
          "tag:role": demo-ansible-tag-role
      register: ec2

    - debug:
        var: ec2

    - name: Retrive instance ids
      set_fact:
        delete_ids: "{{ ec2.instances | json_query(query) }}"
      vars:
        query: "[*].instance_id"

    - debug: var=delete_ids

    - name: Delete instances
      ec2:
        state: absent
        instance_ids: "{{ delete_ids }}"
        region: ap-northeast-1
      when: delete_ids | length > 0

