- hosts: all
  connection: local
  tasks:
    - ec2_instance_info:
        region: ap-northeast-1
      register: ret

    - debug:
        var: ret

    - ec2:
        key_name: aitac-keypair-master
        instance_type: "{{ AWS_INSTANCE_TYPE | default('t2.micro')}}"
        image: ami-06a46da680048c8ae
        wait: yes
        group: aitac-automation-sg
        count: "{{ AWS_INSTANCE_NUM | default(0) }}"
        vpc_subnet_id: subnet-41ab9008
        assign_public_ip: yes
        region: ap-northeast-1
        instance_tags:
          Name: ansible-demo-tag-name
          role: ansible-demo-tag-role
