- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - fetch:
        src: "{{ fullpath_of_logfile }}"
        dest: "./fetched_files/{{ tower_user_name }}"
      register: ret

    - debug: var=ret
