- hosts: all
  gather_facts: no
  tasks:
    - mail:
        host: localhost
        to: root
        subject: Ansible Mail {{ mail_subject | default('テストメール') }}
        body: |
          これはテストメールです。
          Ansibleから送信されました。
          ansible version {{ ansible_version }}
        attach: "{{ atached_file_path | default('/dummy') }}"
        charset: utf-8
