- job_template: job-true
  success:
    - job_template: job-true
      success:
        - job_template: job-true
  failure:
    - job_template: job-true
      success:
        - job_template: job-true

